name: Build and Test

on:
  push:

jobs:
  docker:
    name: Build and Test

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # This matches the Ubuntu version used in our Travis releases
        os: [ubuntu-20.04]
        # This doesn't add platform specific hardware in actual, just an array of platforms to emulate
        arch: [
          linux/amd64,
          linux/arm64,
          linux/arm/v7
        ]
      # Don't cancel jobs on other platforms if one fails
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Install QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          cache: npm
          node-version: 16

      - name: Install dependencies
        run: NODE_DTRACE_PROVIDER_REQUIRE=hard npm ci

      - name: Lint
        run: npm run lint

      - name: Shadowbox with Docker
        run: |
          export SB_PLATFORM="${{ matrix.arch }}"
          export SB_IMAGE="shadowbox-test"

          npm run action shadowbox/docker/build
          bash scripts/install_server.sh --hostname test
